### ISSUE TITLE
Migrations/seeds doesn't work in Docker and production

### ISSUE THREAD

**Issue by joenas** [sheshbabu/freshlytics#24]
Because `src/server/migrations` isn't included at all and not `ts-node` and required directories either. 
Could be fixed by using a `npm run migrate:prod` for example. If I find some time in the coming days I'll put up a PR!

**Comment by sheshbabu** [comment]
Thanks for pointing this out! Must have missed it when we refactored the dockerfile few weeks back. Sorry about the bad experience! 😞

**Comment by joenas** [comment]
No worries, it was an rather easy fix just adding the files to the container manually and running it but for others it might be good to fix 🙂

**Comment by mzch** [comment]
Docker image still has this bug. When could you fix this?

**Comment by sheshbabu** [comment]
@mzch Terribly sorry! I can't spend much time on this for the next couple of months. Would appreciate a PR if possible :)

**Comment by mzch** [comment]
I tried to rebuild freshlytics from sources, and when doing `npm run migrate`, it reported as below:
```
error: server "pipelinedb" does not exist
    at Connection.parseE (/srv/freshlytics/freshlytics/node_modules/pg/lib/connection.js:602:11)
    at Connection.parseMessage (/srv/freshlytics/freshlytics/node_modules/pg/lib/connection.js:399:19)
    at Socket.<anonymous> (/srv/freshlytics/freshlytics/node_modules/pg/lib/connection.js:121:22)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:181:23)
```
Yes, no foreign server `pipelinedb`. 
And if it's fixed by adding `CREATE SERVER "pipelinedb" FOREIGN DATA WRAPPER postgres_fdw;` to sql, then `CREATE VIEW ... WITH (actioin=materialize)` caused error, too.
```
error: unrecognized parameter "action"
    at Connection.parseE (/srv/freshlytics/freshlytics/node_modules/pg/lib/connection.js:602:11)
    at Connection.parseMessage (/srv/freshlytics/freshlytics/node_modules/pg/lib/connection.js:399:19)
    at Socket.<anonymous> (/srv/freshlytics/freshlytics/node_modules/pg/lib/connection.js:121:22)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:181:23)
```

How can this be fixed? Using PostgreSQL 11 and 12 both has the same error.

**Comment by sheshbabu** [comment]
@joenas @mzch This should be fixed in the latest build, sorry for the delay.
